//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard
    {
        public int SequenceID { get; set; }
        public Nullable<int> DashBoardID { get; set; }
        public Nullable<int> WidgetID { get; set; }
        public Nullable<int> PositionTop { get; set; }
        public Nullable<int> PositionLeft { get; set; }
        public Nullable<int> WidgetWidth { get; set; }
        public Nullable<int> WidgetHeight { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual WidgetDetail WidgetDetail { get; set; }
    }
}
